init
oithxs/club_magazine pull request #10
Opened 2018-03-02 04:30 UTC by chocobo777

2018-03-02 05:15 UTC, odanado commented on main.tex
> +\{build/chocobo}
ここは `\input{build/chocobo}` です

2018-03-02 05:16 UTC, odanado commented on main.tex
> +\{build/chocobo}
修正したらgit push する前に `git pull origin ブランチ名` を実行して下さい

2018-03-02 05:21 UTC, odanado commented
https://qiita.com/elzup/items/4c92a2abdab56db3fb4e
`~/.gitignore_global` に `.DS_Store` を書いておいたほうがいい

2018-03-02 05:25 UTC, odanado commented on main.tex
> +\input{build/chocobo}
READMEが間違っていて， `\input{build/chocobo}` ではなく `\input{build/articles/chocobo}` でした

2018-03-02 05:33 UTC, odanado commented
目に見えない文字を表示する設定
https://blog.bouzuya.net/2017/06/23/

2018-03-02 05:56 UTC, odanado commented
https://53-112707429-gh.circle-artifacts.com/0/home/circleci/work/main.pdf

2018-03-02 06:34 UTC, odanado commented
git commit したファイルを消すには， `rm` じゃなくて `git rm` する必要あり

2018-04-30 09:25 UTC, eliza0x reviewed
...

2018-04-30 09:28 UTC, eliza0x requested changes
レビューしました。markdownの記法に関するものしか問題は見つかりませんでした。

2018-04-30 09:28 UTC, eliza0x commented on articles/chocobo/chocobo.md
> +## 参考になったサイト、本
列挙する場合は `-` を行頭に配置すると良いです。

2018-04-30 09:28 UTC, eliza0x commented on articles/chocobo/chocobo.md
> +https://github.com/chocobo777/othello
URLは `<` `>` で囲むとハイパーリンクとして機能します。

2018-04-30 13:16 UTC, chocobo777 commented
修正しました🙇‍♀️

2018-05-01 03:13 UTC, eliza0x requested changes

2018-05-01 03:13 UTC, eliza0x commented on articles/chocobo/chocobo.md
> +オセロAI(odan's diary)
https://qiita.com/tbpgr/items/989c6badefff69377da7#%E8%A8%98%E8%BF%B0%E4%BE%8B
列挙する部分が違うのでは？

2018-05-14 23:51 UTC, eliza0x commented
LGTM

2018-05-14 23:52 UTC, eliza0x submitted a review, later dismissed

2018-05-27 15:47 UTC, odanado approved these changes

2018-05-27 15:47 UTC, merged