[WIP] odanの記事
oithxs/club_magazine pull request #7
Opened 2018-02-12 07:17 UTC by odanado

2018-02-26 17:49 UTC, odanado commented
内容的には完成かな？

2018-03-07 16:34 UTC, akachocobo7 requested changes
47行目の 「 `(` 周辺の... 」 ですがpdfで見ると分かりにくく感じたので、「 `( )`周辺の... 」 や 「カッコ周辺の... 」と直した方が分かりやすいと思います。あと細かいところですが、markdownとMarkdownで表記ゆれができてます。

2018-04-24 13:55 UTC, odanado commented
遅れて申し訳ない 🙏

2018-04-28 04:44 UTC, chocobo777 commented
> 遅れて申し訳ない 🙏
全然問題ないです！むしろ私がslackでお声かけしておくべきでした😇 

記事の方ですが、誤字脱字やおかしな表現といったものは無かったと思います🙆

2018-04-28 04:48 UTC, odanado commented
レビューありがとうございます
approveしてラベルをLGTMにしてください！

2018-04-28 04:51 UTC, akachocobo7 submitted a review, later dismissed

2018-05-27 05:02 UTC, odanado commented
なんでtextlint落ちるん...

2018-05-27 05:07 UTC, siberiy4 approved these changes

2018-05-27 05:08 UTC, merged